# Conclusion {#chap-conclusion}

L'environnement de travail de R et RStudio permet de produire tous types de documents avec un langage unique.

L'objectif de reproductibilité des résultats est atteint en intégrant les traitements statistiques et la rédaction. 
Le travail collaboratif est permis par l'utilisation systématique du contrôle de source et de GitHub.
La présentation des résultats est assurée par les pages GitHub et des modèles de documents couvrant la majorité des besoins.

Pour les pauses, R fournit même quelques jeux dans le package **fun**, dont le célèbre démineur:
```{r mine_sweeper, eval=FALSE}
# Installation du package
install.packages("fun")
# Ouverture d'une fenêtre X et exécution
if (interactive()) {
    if (.Platform$OS.type == "windows") 
        x11() else x11(type = "Xlib")
    fun::mine_sweeper()
}
```

Ce document n'a pas pour objectif d'être exhaustif sur les possibilités de R mais plutôt de présenter une méthode de travail et des moyens simples de l'appliquer rapidement.
On se reportera aux ouvrages plus détaillés cités dans le texte pour approfondir tel ou tel point.

Il est mis à jour régulièrement en fonction de l'évolution des outils disponibles.
